services:
  - type: web
    name: foodles-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    domains:
      - api.foodles.shop
